Update dependencies to latest native0.4 compatible versions
scala/toolkit pull request #46
Opened 2024-05-14 08:22 UTC by adpi2

The goal is to make one final release for Scala Native 0.4 before we switch to Scala Native 0.5.

~~I intend to release this as `0.2.2` even if I bumped the minor version of upickle from `3.1` to `3.2`. I think this is okay because we are in the experimental `0.x` phase, and other dependencies are still milestones with no compat guarantees anyway.~~

I intend to release this as `0.3.0`.

2024-05-14 12:26 UTC, bishabosha commented on changelog/0.2.2/toolkit-test_0.2.2_2.13_changelog.md
> + - Updated `com.lihaoyi:ujson_2.13:3.1.3` from `3.1.3` to `3.2.0` under `com.lihaoyi:upickle_2.13:3.1.4` ILLEGAL CHANGE (required at least: MinorUpdate)
this illegal change looks scary

2024-05-14 12:28 UTC, bishabosha requested changes
it seems like it shouldn't be a patch version change

2024-05-15 07:28 UTC, adpi2 commented
@bishabosha I re-generated the changelog for `0.3.0` please review

2024-05-15 07:41 UTC, bishabosha approved these changes

2024-05-15 08:06 UTC, merged